### ISSUE TITLE
Correct Authorship

### ISSUE THREAD

**Issue by fractastical** [swarmfund/networkdemocracy#1]
@FabrizioRomanoGenovese in a conversation earlier today @wires mentioned that he had contributed substantially to the latest version fo this doc, which I assume is the most recent here. Can we also attribute authorship to him? Potentially should also be credited.

**Comment by FabrizioRomanoGenovese** [comment]
Absolutely. We figured out the details of the algorithm together. There are some minor ads I have to do, I'll add them to the PDF in the next few hours.

**Comment by FabrizioRomanoGenovese** [comment]
Ok, I changed the name. Moreover, I implemented some minor changes.
